name: Red-wine-Predictor
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          echo "Beginning Training"
          python train.py
          
          echo "## Confusion Metrics of Models" >> experiment-report.md
          cml-publish Logistic_Regressionconfusion.png --md >> experiment-report.md
          
          echo "## Performance of Selected Models" >> experiment-report.md
          cat  Results.txt >> experiment-report.md
          
          cml-send-comment experiment-report.md
          
          
