name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "## Model metrics" > report.md
          cat Results.txt >> report.md
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Data viz" >> report.md
          cml-publish Logistic_Regressionconfusion.png --md >> report.md
          cml-publish Random_Forestconfusion.png --md >> report.md
          
          cml-send-comment report.md
