name: Red-wine-Predictor
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          echo "Beginning Training"
          python train.py 
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat Results.txt >> report.md
          cml-send-comment report.md
          cat Results.txt >> report.md
          cml-send-comment report.md
          
          
